name: mentoria_clean_arch
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^1.5.4
  logger: ^1.1.0
  retrofit: ^3.3.1
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
